#This configuration file contains custom configuration parameters for the WA State avian-flue-whole-genome build
build_name: h5n1-franklin-county-whole-genome
subtype: h5n1
segments:
  - pb2
  - pb1
  - pa
  - ha
  - np
  - na
  - mp
  - ns
#reference_files: "config/reference_h5n1_{segment}.gb"
#sequence_files: "test_data/fasta/{segment}_sequences.fasta"
#metadata: "test_data/metadata/merged_metadata.tsv"
#include: "ingest_files_manuscript/includes.txt"
#exclude: "ingest_files_manuscript/excludes.txt"
#colors: "config/colors_h5n1-franklin-county-outbreak.tsv"
#auspice_config: "config/auspice_config_h5n1-franklin-county-outbreak.json"
#new_sequences: "ingest_files_manuscript/Franklin03.fas"
realign_reference: "config/h5_cattle_genome_root.gb"
output_dir: "results"
export_prefix: "auspice/avian-flu_{build_name}.json"

files:
    reference_files: "config/reference_h5n1_{segment}.gb"
    sequences: "test_data/fasta/{segment}_sequences.fasta"
    metadata: "test_data/metadata/merged_metadata.tsv"
    include: "test_data/includes.txt"
    exclude: "test_data/excludes.txt"
    colors: "config/colors_h5n1-franklin-county-outbreak.tsv"
    auspice_config: "config/auspice_config_h5n1-franklin-county-outbreak.json"

subsampling:
    max_sequences: 100
